// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

#include <ArduinoWebsockets.h>
#ifdef ARDUINO_ARCH_ESP32
#include <WiFi.h>
#else
#include <ESP8266WiFi.h>
#endif

#include <mcp_can.h>
#include <SPI.h>


const char DEVICE_LOGIN_NAME[]  = "18ecb346-46af-46f1-ba84-4aff2b92fe61";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSetpointChange();
void onTerrenoChange();
void onTerreno2Change();
void onTerreno3Change();

float presion;
float setpoint;
bool terreno;
bool terreno2;
bool terreno3;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(presion, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(setpoint, READWRITE, ON_CHANGE, onSetpointChange);
  ArduinoCloud.addProperty(terreno, READWRITE, ON_CHANGE, onTerrenoChange);
  ArduinoCloud.addProperty(terreno2, READWRITE, ON_CHANGE, onTerreno2Change);
  ArduinoCloud.addProperty(terreno3, READWRITE, ON_CHANGE, onTerreno3Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
